name: speedshare
description: "Fast local file sharing across devices on the same network. No internet required."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  mime: ^2.0.0
  path: ^1.8.3
  intl: ^0.18.1
  open_file: ^3.3.2
  url_launcher: ^6.1.14
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  animate_do: ^4.2.0
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  http: ^1.2.1

  desktop_drop: ^0.6.0
  window_size: ^0.1.0
  network_info_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
